# Makefile for CS689 Language Processing Assignment 1
# Submitted by: 231110032

# Variables
CORPUS_URL = https://huggingface.co/datasets/ai4bharat/naamapadam/tree/main/data
CORPUS_FILE = gu_IndicNER_v1.0.zip



